"""
NEXUS-NER Phase 7D — Public Citizen Reporting & Verification Tests

Coverage:
1. PUBLIC can submit a report.
2. New reports start UNVERIFIED.
3. Reporter identity is bound to the authenticated PUBLIC user.
4. PUBLIC can view its own report.
5. PUBLIC cannot view another PUBLIC user's report.
6. PUBLIC cannot access the operational review queue.
7. DRIVER cannot verify/reject reports.
8. Out-of-NER coordinates are rejected.
9. Authorized reviewer can verify a critical report.
10. Verification creates a VERIFIED Incident.
11. Critical verification blocks the affected Road and raises risk to 95.
12. Operational verification response contains reviewer audit fields.
13. PUBLIC report response hides reviewer/internal verification fields.
14. Duplicate verification is rejected.
15. Authorized reviewer can reject a report.
16. Duplicate rejection is rejected.
"""

import os
import sys
import time
import unittest

from fastapi.testclient import TestClient

backend_path = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "backend")
)
if backend_path not in sys.path:
    sys.path.insert(0, backend_path)

from app.main import app
from app.database import SessionLocal
from app.models.alert import Alert
from app.models.incident import Incident
from app.models.public_report import PublicReport
from app.models.road import Road
from app.models.user import User
from app.services import auth_service


class Phase7DPublicReportTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.client = TestClient(app)
        cls.db = SessionLocal()

        auth_service.seed_initial_users_if_empty(cls.db)

        cls.admin_token = cls._login("admin", "Admin@Nexus2026")
        cls.operator_token = cls._login("operator", "Operator@Nexus2026")
        cls.field_token = cls._login("field_officer", "Field@Nexus2026")
        cls.driver_token = cls._login("driver", "Driver@Nexus2026")

        timestamp = int(time.time() * 1000)

        cls.public_username = f"test_phase7d_public_{timestamp}"
        cls.public_email = f"{cls.public_username}@example.com"
        cls.public_password = "Phase7DPublic123!"

        response = cls.client.post(
            "/auth/register",
            json={
                "username": cls.public_username,
                "email": cls.public_email,
                "password": cls.public_password,
            },
        )

        if response.status_code != 201:
            raise RuntimeError(
                "Could not create Phase 7D PUBLIC test user: "
                f"{response.status_code} {response.text}"
            )

        cls.public_token = cls._login(
            cls.public_username,
            cls.public_password,
        )
        cls.public_user_id = cls._get_user_id(cls.public_username)

        # Create a second PUBLIC user to verify horizontal ownership protection.
        cls.second_public_username = f"test_phase7d_public2_{timestamp}"
        cls.second_public_email = f"{cls.second_public_username}@example.com"
        cls.second_public_password = "Phase7DPublic2123!"

        response = cls.client.post(
            "/auth/register",
            json={
                "username": cls.second_public_username,
                "email": cls.second_public_email,
                "password": cls.second_public_password,
            },
        )

        if response.status_code != 201:
            raise RuntimeError(
                "Could not create second Phase 7D PUBLIC test user: "
                f"{response.status_code} {response.text}"
            )

        cls.second_public_token = cls._login(
            cls.second_public_username,
            cls.second_public_password,
        )
        cls.second_public_user_id = cls._get_user_id(
            cls.second_public_username
        )

        cls.test_road = cls.db.query(Road).first()
        if cls.test_road is None:
            raise RuntimeError(
                "Phase 7D tests require at least one Road record."
            )

        cls.original_road_status = cls.test_road.status
        cls.original_road_risk_score = cls.test_road.risk_score

        cls.created_report_ids = []
        cls.created_incident_ids = []
        cls.created_alert_ids = []

    @classmethod
    def tearDownClass(cls):
        try:
            # Delete alerts generated by these tests.
            if cls.created_alert_ids:
                cls.db.query(Alert).filter(
                    Alert.id.in_(cls.created_alert_ids)
                ).delete(synchronize_session=False)

            # Delete incidents generated by these tests.
            if cls.created_incident_ids:
                cls.db.query(Incident).filter(
                    Incident.id.in_(cls.created_incident_ids)
                ).delete(synchronize_session=False)

            # Delete reports generated by these tests.
            if cls.created_report_ids:
                cls.db.query(PublicReport).filter(
                    PublicReport.id.in_(cls.created_report_ids)
                ).delete(synchronize_session=False)

            # Restore the road state.
            road = cls.db.query(Road).filter(
                Road.id == cls.test_road.id
            ).first()

            if road:
                road.status = cls.original_road_status
                road.risk_score = cls.original_road_risk_score

            # Delete only the dedicated test users.
            cls.db.query(User).filter(
                User.id.in_(
                    [
                        cls.public_user_id,
                        cls.second_public_user_id,
                    ]
                )
            ).delete(synchronize_session=False)

            cls.db.commit()

        except Exception:
            cls.db.rollback()
        finally:
            cls.db.close()

    @classmethod
    def _login(cls, username: str, password: str) -> str:
        response = cls.client.post(
            "/auth/login",
            json={
                "username": username,
                "password": password,
            },
        )

        if response.status_code != 200:
            raise RuntimeError(
                f"Login failed for '{username}': "
                f"{response.status_code} {response.text}"
            )

        return response.json()["access_token"]

    @classmethod
    def _get_user_id(cls, username: str) -> int:
        user = cls.db.query(User).filter(
            User.username == username
        ).first()

        if user is None:
            raise RuntimeError(
                f"Test user '{username}' was not found."
            )

        return user.id

    @staticmethod
    def _headers(token: str) -> dict:
        return {
            "Authorization": f"Bearer {token}",
        }

    def _create_report(
        self,
        *,
        token: str,
        description: str,
        severity_hint: str = "high",
        road_id=None,
    ):
        payload = {
            "latitude": 26.1445,
            "longitude": 91.7362,
            "report_type": "LANDSLIDE",
            "description": description,
            "severity_hint": severity_hint,
        }

        if road_id is not None:
            payload["road_id"] = road_id

        response = self.client.post(
            "/public-reports/",
            json=payload,
            headers=self._headers(token),
        )

        if response.status_code == 201:
            self.__class__.created_report_ids.append(
                response.json()["id"]
            )

        return response

    def _verify_report(
        self,
        report_id: int,
        token: str,
        *,
        severity: str = "high",
        notes: str = "Verified by field operations.",
    ):
        response = self.client.patch(
            f"/public-reports/{report_id}/verify",
            json={
                "verification_notes": notes,
                "severity": severity,
            },
            headers=self._headers(token),
        )

        if response.status_code == 200:
            incident_id = response.json().get(
                "converted_incident_id"
            )
            if incident_id:
                self.__class__.created_incident_ids.append(
                    incident_id
                )

        return response

    def test_01_public_can_submit_report(self):
        response = self._create_report(
            token=self.public_token,
            description="Large landslide blocking an essential-goods corridor.",
            severity_hint="critical",
        )

        self.assertEqual(response.status_code, 201, response.text)

        data = response.json()

        self.assertIsNotNone(data.get("id"))
        self.assertEqual(data["status"], "UNVERIFIED")
        self.assertEqual(
            data["reporter_user_id"],
            self.public_user_id,
        )

        print(
            "PASS: Scenario 1 - PUBLIC can submit a report and it starts UNVERIFIED."
        )

    def test_02_public_can_view_own_report_without_internal_fields(self):
        response = self._create_report(
            token=self.public_token,
            description="Own-report visibility and privacy test.",
        )

        self.assertEqual(response.status_code, 201, response.text)

        report_id = response.json()["id"]

        response = self.client.get(
            f"/public-reports/{report_id}",
            headers=self._headers(self.public_token),
        )

        self.assertEqual(response.status_code, 200, response.text)

        data = response.json()

        self.assertEqual(data["id"], report_id)
        self.assertIsNone(data.get("reviewed_by_user_id"))
        self.assertIsNone(data.get("verification_notes"))

        print(
            "PASS: Scenario 2 - PUBLIC can view own report without internal reviewer fields."
        )

    def test_03_public_cannot_view_another_public_users_report(self):
        response = self._create_report(
            token=self.public_token,
            description="Horizontal ownership protection test.",
        )

        self.assertEqual(response.status_code, 201, response.text)

        report_id = response.json()["id"]

        response = self.client.get(
            f"/public-reports/{report_id}",
            headers=self._headers(self.second_public_token),
        )

        self.assertEqual(response.status_code, 403, response.text)

        print(
            "PASS: Scenario 3 - PUBLIC cannot access another citizen's report."
        )

    def test_04_public_cannot_access_review_queue(self):
        response = self.client.get(
            "/public-reports/",
            headers=self._headers(self.public_token),
        )

        self.assertEqual(response.status_code, 403, response.text)

        print(
            "PASS: Scenario 4 - PUBLIC denied access to operational review queue."
        )

    def test_05_driver_cannot_verify_report(self):
        response = self._create_report(
            token=self.public_token,
            description="Driver authorization boundary test.",
        )

        self.assertEqual(response.status_code, 201, response.text)

        report_id = response.json()["id"]

        response = self._verify_report(
            report_id,
            self.driver_token,
            severity="high",
            notes="Unauthorized driver attempt.",
        )

        self.assertEqual(response.status_code, 403, response.text)

        print(
            "PASS: Scenario 5 - DRIVER cannot verify public reports."
        )

    def test_06_out_of_ner_coordinates_rejected(self):
        response = self.client.post(
            "/public-reports/",
            json={
                "latitude": 18.5000,
                "longitude": 91.7362,
                "report_type": "LANDSLIDE",
                "description": "Report outside the NER test boundary.",
                "severity_hint": "high",
            },
            headers=self._headers(self.public_token),
        )

        self.assertEqual(response.status_code, 400, response.text)
        self.assertIn(
            "outside Northeast India Region bounds",
            response.json()["detail"],
        )

        print(
            "PASS: Scenario 6 - Out-of-NER coordinates are rejected."
        )

    def test_07_authorized_operator_can_verify_critical_report(self):
        road = self.test_road

        response = self._create_report(
            token=self.public_token,
            description="Critical landslide requiring operational verification.",
            severity_hint="critical",
            road_id=road.id,
        )

        self.assertEqual(response.status_code, 201, response.text)

        report_id = response.json()["id"]

        response = self._verify_report(
            report_id,
            self.operator_token,
            severity="critical",
            notes="Verified by control operator.",
        )

        self.assertEqual(response.status_code, 200, response.text)

        data = response.json()

        self.assertEqual(data["status"], "VERIFIED")
        self.assertIsNotNone(data["converted_incident_id"])
        self.assertIsNotNone(data["reviewed_by_user_id"])
        self.assertIsNotNone(data["verification_notes"])

        self.db.refresh(road)

        self.assertEqual(road.status, "blocked")
        self.assertEqual(road.risk_score, 95)

        incident = self.db.query(Incident).filter(
            Incident.id == data["converted_incident_id"]
        ).first()

        self.assertIsNotNone(incident)
        self.assertEqual(incident.status, "verified")
        self.assertEqual(incident.severity, "critical")
        self.assertEqual(incident.affected_road_id, road.id)
        self.assertEqual(incident.risk_score, 95)

        print(
            "PASS: Scenario 7 - Authorized verification creates a VERIFIED "
            "Incident, blocks the Road, and raises risk to 95."
        )

    def test_08_public_view_after_verification_hides_internal_fields(self):
        response = self._create_report(
            token=self.public_token,
            description="Post-verification public privacy test.",
        )

        self.assertEqual(response.status_code, 201, response.text)

        report_id = response.json()["id"]

        verify_response = self._verify_report(
            report_id,
            self.operator_token,
            severity="medium",
            notes="Internal verification note.",
        )

        self.assertEqual(
            verify_response.status_code,
            200,
            verify_response.text,
        )

        response = self.client.get(
            f"/public-reports/{report_id}",
            headers=self._headers(self.public_token),
        )

        self.assertEqual(response.status_code, 200, response.text)

        data = response.json()

        self.assertEqual(data["status"], "VERIFIED")
        self.assertIsNone(data.get("reviewed_by_user_id"))
        self.assertIsNone(data.get("verification_notes"))

        print(
            "PASS: Scenario 8 - PUBLIC cannot see reviewer identity/internal notes after verification."
        )

    def test_09_duplicate_verification_blocked(self):
        response = self._create_report(
            token=self.public_token,
            description="Duplicate verification protection test.",
            severity_hint="high",
        )

        self.assertEqual(response.status_code, 201, response.text)

        report_id = response.json()["id"]

        first = self._verify_report(
            report_id,
            self.operator_token,
            severity="high",
            notes="First verification.",
        )

        self.assertEqual(first.status_code, 200, first.text)

        second = self._verify_report(
            report_id,
            self.operator_token,
            severity="high",
            notes="Second verification attempt.",
        )

        self.assertEqual(second.status_code, 400, second.text)

        print(
            "PASS: Scenario 9 - Duplicate verification is blocked."
        )

    def test_10_authorized_field_officer_can_reject_report(self):
        response = self._create_report(
            token=self.public_token,
            description="Report rejection workflow test.",
            severity_hint="low",
        )

        self.assertEqual(response.status_code, 201, response.text)

        report_id = response.json()["id"]

        response = self.client.patch(
            f"/public-reports/{report_id}/reject",
            json={
                "rejection_reason": "Insufficient supporting evidence.",
            },
            headers=self._headers(self.field_token),
        )

        self.assertEqual(response.status_code, 200, response.text)

        data = response.json()

        self.assertEqual(data["status"], "REJECTED")
        self.assertEqual(
            data["rejection_reason"],
            "Insufficient supporting evidence.",
        )
        self.assertIsNotNone(data["reviewed_by_user_id"])

        print(
            "PASS: Scenario 10 - FIELD_OFFICER can reject a report with an audit reason."
        )

    def test_11_duplicate_rejection_blocked(self):
        response = self._create_report(
            token=self.public_token,
            description="Duplicate rejection protection test.",
            severity_hint="low",
        )

        self.assertEqual(response.status_code, 201, response.text)

        report_id = response.json()["id"]

        first = self.client.patch(
            f"/public-reports/{report_id}/reject",
            json={
                "rejection_reason": "First rejection.",
            },
            headers=self._headers(self.field_token),
        )

        self.assertEqual(first.status_code, 200, first.text)

        second = self.client.patch(
            f"/public-reports/{report_id}/reject",
            json={
                "rejection_reason": "Second rejection attempt.",
            },
            headers=self._headers(self.field_token),
        )

        self.assertEqual(second.status_code, 400, second.text)

        print(
            "PASS: Scenario 11 - Duplicate rejection is blocked."
        )


if __name__ == "__main__":
    unittest.main()